const INDIAN_COMPANIES = {
  "RELIANCE": "Reliance Industries Ltd",
  "TCS": "Tata Consultancy Services Ltd",
  "HDFCBANK": "HDFC Bank Ltd",
  "ICICIBANK": "ICICI Bank Ltd",
  "INFY": "Infosys Ltd",
  "HINDUNILVR": "Hindustan Unilever Ltd",
  "ITC": "ITC Ltd",
  "SBIN": "State Bank of India",
  "BHARTIARTL": "Bharti Airtel Ltd",
  "KOTAKBANK": "Kotak Mahindra Bank Ltd",
  "AXISBANK": "Axis Bank Ltd",
  "LT": "Larsen & Toubro Ltd",
  "BAJFINANCE": "Bajaj Finance Ltd",
  "ASIANPAINT": "Asian Paints Ltd",
  "MARUTI": "Maruti Suzuki India Ltd",
  "TITAN": "Titan Company Ltd",
  "SUNPHARMA": "Sun Pharmaceutical Industries Ltd",
  "TATAMOTORS": "Tata Motors Ltd",
  "ULTRACEMCO": "UltraTech Cement Ltd",
  "NESTLEIND": "Nestle India Ltd",
  "WIPRO": "Wipro Ltd",
  "POWERGRID": "Power Grid Corporation of India Ltd",
  "NTPC": "NTPC Ltd",
  "M_M": "Mahindra & Mahindra Ltd",
  "ADANIENT": "Adani Enterprises Ltd",
  "ADANIGREEN": "Adani Green Energy Ltd",
  "ADANIPORTS": "Adani Ports & SEZ Ltd",
  "ADANIPOWER": "Adani Power Ltd",
  "COALINDIA": "Coal India Ltd",
  "ONGC": "Oil & Natural Gas Corporation Ltd",
  "TATASTEEL": "Tata Steel Ltd",
  "HCLTECH": "HCL Technologies Ltd",
  "TECHM": "Tech Mahindra Ltd",
  "INDUSINDBK": "IndusInd Bank Ltd",
  "JSWSTEEL": "JSW Steel Ltd",
  "GRASIM": "Grasim Industries Ltd",
  "HDFCLIFE": "HDFC Life Insurance Company Ltd",
  "SBILIFE": "SBI Life Insurance Company Ltd",
  "BRITANNIA": "Britannia Industries Ltd",
  "APOLLOHOSP": "Apollo Hospitals Enterprise Ltd",
  "EICHERMOT": "Eicher Motors Ltd",
  "BAJAJ_AUTO": "Bajaj Auto Ltd",
  "TATACONSUM": "Tata Consumer Products Ltd",
  "DIVISLAB": "Divis Laboratories Ltd",
  "DRREDDY": "Dr Reddy's Laboratories Ltd",
  "HEROMOTOCO": "Hero MotoCorp Ltd",
  "CIPLA": "Cipla Ltd",
  "UPL": "UPL Ltd",
  "BPCL": "Bharat Petroleum Corporation Ltd",
  "IOC": "Indian Oil Corporation Ltd",
  "GAIL": "GAIL (India) Ltd",
  "SHREECEM": "Shree Cement Ltd",
  "DABUR": "Dabur India Ltd",
  "HINDALCO": "Hindalco Industries Ltd",
  "VEDL": "Vedanta Ltd",
  "TATAPOWER": "Tata Power Company Ltd",
  "SIEMENS": "Siemens Ltd",
  "PIDILITIND": "Pidilite Industries Ltd",
  "BERGEPAINT": "Berger Paints India Ltd",
  "GODREJCP": "Godrej Consumer Products Ltd",
  "MARICO": "Marico Ltd",
  "COLPAL": "Colgate-Palmolive (India) Ltd",
  "HAVELLS": "Havells India Ltd",
  "AMBUJACEM": "Ambuja Cements Ltd",
  "ACC": "ACC Ltd",
  "BOSCHLTD": "Bosch Ltd",
  "ABB": "ABB India Ltd",
  "BEL": "Bharat Electronics Ltd",
  "HAL": "Hindustan Aeronautics Ltd",
  "BHEL": "Bharat Heavy Electricals Ltd",
  "NMDC": "NMDC Ltd",
  "SAIL": "Steel Authority of India Ltd",
  "CONCOR": "Container Corporation of India Ltd",
  "IRCTC": "Indian Railway Catering & Tourism Corporation Ltd",
  "IRFC": "Indian Railway Finance Corporation Ltd",
  "RVNL": "Rail Vikas Nigam Ltd",
  "PFC": "Power Finance Corporation Ltd",
  "RECLTD": "REC Ltd",
  "NHPC": "NHPC Ltd",
  "SJVN": "SJVN Ltd",
  "NLCINDIA": "NLC India Ltd",
  "OIL": "Oil India Ltd",
  "GICRE": "General Insurance Corporation of India",
  "LICHSGFIN": "LIC Housing Finance Ltd",
  "CANBK": "Canara Bank",
  "BANKBARODA": "Bank of Baroda",
  "IOB": "Indian Overseas Bank",
  "UCOBANK": "UCO Bank",
  "CENTRALBK": "Central Bank of India",
  "PNB": "Punjab National Bank",
  "UNIONBANK": "Union Bank of India",
  "IDFCFIRSTB": "IDFC First Bank Ltd",
  "FEDERALBNK": "The Federal Bank Ltd",
  "RBLBANK": "RBL Bank Ltd",
  "BANDHANBNK": "Bandhan Bank Ltd",
  "AUBANK": "AU Small Finance Bank Ltd",
  "EQUITASBNK": "Equitas Small Finance Bank Ltd",
  "UJJIVANSFB": "Ujjivan Small Finance Bank Ltd",
  "J_KBANK": "Jammu & Kashmir Bank Ltd",
  "KARURVYSYA": "Karur Vysya Bank Ltd",
  "SOUTHBANK": "South Indian Bank Ltd",
  "CITYUNION": "City Union Bank Ltd",
  "DCBBANK": "DCB Bank Ltd",
  "TMB": "Tamilnad Mercantile Bank Ltd",
  "CSBBANK": "CSB Bank Ltd",
  "KTKBANK": "Karnataka Bank Ltd",
  "INDIANB": "Indian Bank",
  "PSB": "Punjab & Sind Bank",
  "MAHABANK": "Bank of Maharashtra",
  "JIOFIN": "Jio Financial Services Ltd",
  "PAYTM": "One 97 Communications Ltd (Paytm)",
  "ZOMATO": "Zomato Ltd",
  "POLYCAB": "Polycab India Ltd",
  "ASTRAL": "Astral Ltd",
  "DIXON": "Dixon Technologies (India) Ltd",
  "CROMPTON": "Crompton Greaves Consumer Electricals Ltd",
  "VGUARD": "V-Guard Industries Ltd",
  "KAJARIACER": "Kajaria Ceramics Ltd",
  "CERA": "Cera Sanitaryware Ltd",
  "SOMANY": "Somany Ceramics Ltd",
  "JUBLFOOD": "Jubilant FoodWorks Ltd",
  "DEVYANI": "Devyani International Ltd",
  "WESTLIFE": "Westlife Development Ltd",
  "TRENT": "Trent Ltd",
  "ABFRL": "Aditya Birla Fashion & Retail Ltd",
  "VMART": "V-Mart Retail Ltd",
  "DMART": "Avenue Supermarts Ltd",
  "SHOPERSTOP": "Shoppers Stop Ltd",
  "KALYANKJIL": "Kalyan Jewellers India Ltd",
  "PCJEWELLER": "PC Jeweller Ltd",
  "THANGAMAYL": "Thangamayil Jewellery Ltd",
  "SENCO": "Senco Gold Ltd",
  "PNGJL": "PNG Jewellers Ltd",
  "TBZ": "Tribhovandas Bhimji Zaveri Ltd",
  "TATACHEM": "Tata Chemicals Ltd",
  "TATACOMM": "Tata Communications Ltd",
  "TATAINVEST": "Tata Investment Corporation Ltd",
  "TATAMETALI": "Tata Metaliks Ltd",
  "TATAMTRDVR": "Tata Motors Ltd (DVR)",
  "TATAELXSI": "Tata Elxsi Ltd",
  "TATACOFFEE": "Tata Coffee Ltd",
  "SRF": "SRF Ltd",
  "LUPIN": "Lupin Ltd",
  "AUROPHARMA": "Aurobindo Pharma Ltd",
  "TORNTPHARM": "Torrent Pharmaceuticals Ltd",
  "BIOCON": "Biocon Ltd",
  "ALKEM": "Alkem Laboratories Ltd",
  "GLENMARK": "Glenmark Pharmaceuticals Ltd",
  "CADILAHC": "Cadila Healthcare Ltd",
  "SANOFI": "Sanofi India Ltd",
  "PFIZER": "Pfizer Ltd",
  "ABBOTINDIA": "Abbott India Ltd",
  "GLAXO": "GlaxoSmithKline Pharmaceuticals Ltd",
  "MERCK": "Merck Ltd",
  "FDC": "FDC Ltd",
  "JBCHEPHARM": "JB Chemicals & Pharmaceuticals Ltd",
  "CAPLIPOINT": "Caplin Point Laboratories Ltd",
  "NATCOPHARM": "Natco Pharma Ltd",
  "STAR": "Strides Pharma Science Ltd",
  "SYNGENE": "Syngene International Ltd",
  "LAURUSLABS": "Laurus Labs Ltd",
  "GRANULES": "Granules India Ltd",
  "IPCALAB": "Ipca Laboratories Ltd",
  "AJANTPHARM": "Ajanta Pharma Ltd",
  "GSKCONS": "GlaxoSmithKline Consumer Healthcare Ltd",
  "MCDOWELL_N": "United Spirits Ltd",
  "UBL": "United Breweries Ltd",
  "RADICO": "Radico Khaitan Ltd",
  "TILAKNAGAR": "Tilaknagar Industries Ltd",
  "GLOBUSSPR": "Globus Spirits Ltd",
  "SULA": "Sula Vineyards Ltd",
  "BSE": "BSE Ltd",
  "MCX": "Multi Commodity Exchange of India Ltd",
  "CAMS": "Computer Age Management Services Ltd",
  "CDSL": "Central Depository Services Ltd",
  "ISEC": "ICICI Securities Ltd",
  "HDFCAMC": "HDFC Asset Management Company Ltd",
  "NAM_INDIA": "Nippon Life India Asset Management Ltd",
  "UTIAMC": "UTI Asset Management Company Ltd",
  "ABCAPITAL": "Aditya Birla Capital Ltd",
  "MUTHOOTFIN": "Muthoot Finance Ltd",
  "MANAPPURAM": "Manappuram Finance Ltd",
  "BAJAJHLDNG": "Bajaj Holdings & Investment Ltd",
  "CHOLAFIN": "Cholamandalam Investment & Finance Company Ltd",
  "SHRIRAMFIN": "Shriram Finance Ltd",
  "SRTRANSFIN": "Shriram Transport Finance Company Ltd",
  "POONAWALLA": "Poonawalla Fincorp Ltd",
  "MAHFIN": "Mahindra & Mahindra Financial Services Ltd",
  "IBULHSGFIN": "Indiabulls Housing Finance Ltd",
  "REPCOHOME": "Repco Home Finance Ltd",
  "CANFINHOME": "Can Fin Homes Ltd",
  "PNBHOUSING": "PNB Housing Finance Ltd",
  "GICHSGFIN": "GIC Housing Finance Ltd",
  "APOLLOTYRE": "Apollo Tyres Ltd",
  "MRF": "MRF Ltd",
  "CEATLTD": "CEAT Ltd",
  "JKTYRE": "JK Tyre & Industries Ltd",
  "BALKRISIND": "Balkrishna Industries Ltd",
  "TVSMOTOR": "TVS Motor Company Ltd",
  "ASHOKLEY": "Ashok Leyland Ltd",
  "FORCEMOT": "Force Motors Ltd",
  "SMLISUZU": "SML Isuzu Ltd",
  "ESCORTS": "Escorts Kubota Ltd",
  "SWARAJENG": "Swaraj Engines Ltd",
  "BHARATFORG": "Bharat Forge Ltd",
  "MINDACORP": "Minda Corporation Ltd",
  "MINDAIND": "Minda Industries Ltd",
  "SAMIL": "Samvardhana Motherson International Ltd",
  "SUNDRAMFAST": "Sundram Fasteners Ltd",
  "RACLGEAR": "RACL Geartech Ltd",
  "FIEMIND": "FIEM Industries Ltd",
  "GABRIEL": "Gabriel India Ltd",
  "SUPRAJIT": "Suprajit Engineering Ltd",
  "LUMMAXIND": "Lumax Industries Ltd",
  "WABCOINDIA": "Wabco India Ltd",
  "SCHAEFFLER": "Schaeffler India Ltd",
  "SKFINDIA": "SKF India Ltd",
  "TIMKEN": "Timken India Ltd",
  "GRINDWELL": "Grindwell Norton Ltd",
  "CARBORUNIV": "Carborundum Universal Ltd",
  "WENDT": "Wendt (India) Ltd",
  "HIL": "HIL Ltd",
  "GREENPANEL": "Greenpanel Industries Ltd",
  "GREENPLY": "Greenply Industries Ltd",
  "CENTURYPLY": "Century Plyboards (India) Ltd",
  "KIRLOSENG": "Kirloskar Oil Engines Ltd",
  "KIRLOSBROS": "Kirloskar Brothers Ltd",
  "KIRLOSIND": "Kirloskar Industries Ltd",
  "CUMMINSIND": "Cummins India Ltd",
  "GREAVESCOT": "Greaves Cotton Ltd",
  "KSB": "KSB Ltd",
  "TRITURBINE": "Triveni Turbine Ltd",
  "SANGHIIND": "Sanghi Industries Ltd",
  "JKLAKSHMI": "JK Lakshmi Cement Ltd",
  "JKCEMENT": "JK Cement Ltd",
  "RAMCOCEM": "Ramco Cements Ltd",
  "INDIACEM": "India Cements Ltd",
  "ORIENTCEM": "Orient Cement Ltd",
  "HEIDELBERG": "HeidelbergCement India Ltd",
  "STARCEMENT": "Star Cement Ltd",
  "SAGCEM": "Sagar Cements Ltd",
  "DECCANCE": "Deccan Cements Ltd",
  "NCLIND": "NCL Industries Ltd",
  "BIRLACORPN": "Birla Corporation Ltd",
  "DALBHARAT": "Dalmia Bharat Ltd",
  "HINDZINC": "Hindustan Zinc Ltd",
  "NATIONALUM": "National Aluminium Co Ltd",
  "HINDCOPPER": "Hindustan Copper Ltd",
  "MOIL": "MOIL Ltd",
  "TINPLATE": "Tinplate Company of India Ltd",
  "WELCORP": "Welspun Corp Ltd",
  "JINDALSTEL": "Jindal Steel & Power Ltd",
  "VESUVIUS": "Vesuvius India Ltd",
  "TATASTLBSL": "Tata Steel BSL Ltd",
  "JINDALSAW": "Jindal Saw Ltd",
  "MAHSEAMLES": "Maharashtra Seamless Ltd",
  "RATNAMANI": "Ratnamani Metals & Tubes Ltd",
  "APLAPOLLO": "APL Apollo Tubes Ltd",
  "SURYAROSNI": "Surya Roshni Ltd",
  "PRAKASH": "Prakash Industries Ltd",
  "EMAMILTD": "Emami Ltd",
  "NAUKRI": "Info Edge (India) Ltd",
  "JUSTDIAL": "Just Dial Ltd",
  "INDIAMART": "IndiaMART InterMESH Ltd",
  "EASEMYTRIP": "Easy Trip Planners Ltd",
  "YATRA": "Yatra Online Inc",
  "MMYT": "MakeMyTrip Ltd",
  "RAILTEL": "RailTel Corporation of India Ltd",
  "GATI": "Gati Ltd",
  "BLUEDART": "Blue Dart Express Ltd",
  "TCIEXP": "TCI Express Ltd",
  "VRLLOG": "VRL Logistics Ltd",
  "ALLCARGO": "Allcargo Logistics Ltd",
  "MAHLOG": "Mahindra Logistics Ltd",
  "DELHIVERY": "Delhivery Ltd",
  "SPICEJET": "SpiceJet Ltd",
  "INDIGO": "InterGlobe Aviation Ltd (IndiGo)",
  "AAVAS": "Aavas Financiers Ltd",
  "HOMEFIRST": "Home First Finance Company India Ltd",
  "APTUS": "Aptus Value Housing Finance India Ltd",
  "FIVESTAR": "Five-Star Business Finance Ltd",
  "SUNDARMFIN": "Sundaram Finance Ltd",
  "CHOLAHLDNG": "Cholamandalam Financial Holdings Ltd",
  "L_TFH": "L&T Finance Holdings Ltd",
  "LIC": "Life Insurance Corporation of India",
  "ICICIGI": "ICICI Lombard General Insurance Company Ltd",
  "ICICIPRULI": "ICICI Prudential Life Insurance Company Ltd",
  "HDFCERG": "HDFC ERGO General Insurance Company Ltd",
  "NEWGEN": "Newgen Software Technologies Ltd",
  "KPITTECH": "KPIT Technologies Ltd",
  "LTIM": "LTIMindtree Ltd",
  "PERSISTENT": "Persistent Systems Ltd",
  "COFORGE": "Coforge Ltd",
  "MPHASIS": "Mphasis Ltd",
  "OFSS": "Oracle Financial Services Software Ltd",
  "ZENSARTECH": "Zensar Technologies Ltd",
  "CYIENT": "Cyient Ltd",
  "TATATECH": "Tata Technologies Ltd",
  "SONATSOFTW": "Sonata Software Ltd",
  "TAKE": "Take Solutions Ltd",
  "FIRSTSOURCE": "Firstsource Solutions Ltd",
  "DATAMATICS": "Datamatics Global Services Ltd",
  "MASTEK": "Mastek Ltd",
  "NIITLTD": "NIIT Ltd",
  "HEXAWARE": "Hexaware Technologies Ltd",
  "SASKEN": "Sasken Technologies Ltd",
  "RSYSTEMS": "R Systems International Ltd",
  "INTELLECT": "Intellect Design Arena Ltd",
  "MAPMYINDIA": "MapmyIndia (CE Info Systems Ltd)",
  "POLICYBZR": "PB Fintech Ltd (Policybazaar)",
  "CARTRADE": "CarTrade Tech Ltd",
  "NAZARA": "Nazara Technologies Ltd",
  "ONMOBILE": "OnMobile Global Ltd",
  "TEAMLEASE": "TeamLease Services Ltd",
  "QUESS": "Quess Corp Ltd",
  "SIS": "SIS Ltd",
  "AEGISCHEM": "Aegis Logistics Ltd",
  "GUJFLUORO": "Gujarat Fluorochemicals Ltd",
  "NAVINFLUOR": "Navin Fluorine International Ltd",
  "SUDARSCHEM": "Sudarshan Chemical Industries Ltd",
  "DEEPAKNTR": "Deepak Nitrite Ltd",
  "BALAMINES": "Balaji Amines Ltd",
  "ALKYLAMINE": "Alkyl Amines Chemicals Ltd",
  "CLEAN": "Clean Science and Technology Ltd",
  "FAIRCHEM": "Fairchem Organics Ltd",
  "PIIND": "PI Industries Ltd",
  "BAYERCROP": "Bayer Cropscience Ltd",
  "DHANUKA": "Dhanuka Agritech Ltd",
  "RALLIS": "Rallis India Ltd",
  "COROMANDEL": "Coromandel International Ltd",
  "CHAMBLFERT": "Chambal Fertilisers & Chemicals Ltd",
  "GSFC": "Gujarat State Fertilizers & Chemicals Ltd",
  "FACT": "Fertilizers & Chemicals Travancore Ltd",
  "NFL": "National Fertilizers Ltd",
  "RCF": "Rashtriya Chemicals & Fertilizers Ltd",
  "MANGCHEFER": "Mangalore Chemicals & Fertilizers Ltd",
  "PARADEEP": "Paradeep Phosphates Ltd",
  "KRIBHCO": "Krishak Bharati Cooperative Ltd",
  "IFFCO": "Indian Farmers Fertiliser Cooperative Ltd",
  "PETRONET": "Petronet LNG Ltd",
  "IGL": "Indraprastha Gas Ltd",
  "MGL": "Mahanagar Gas Ltd",
  "GUJGASLTD": "Gujarat Gas Ltd",
  "ATGL": "Adani Total Gas Ltd",
  "HINDPETRO": "Hindustan Petroleum Corporation Ltd",
  "CHENNPETRO": "Chennai Petroleum Corporation Ltd",
  "MRPL": "Mangalore Refinery & Petrochemicals Ltd",
  "NRL": "Numaligarh Refinery Ltd",
  "JSWENERGY": "JSW Energy Ltd",
  "TORNTPOWER": "Torrent Power Ltd",
  "CESC": "CESC Ltd",
  "BFUTILITIE": "BF Utilities Ltd",
  "GMRINFRA": "GMR Infrastructure Ltd",
  "GVKPIL": "GVK Power & Infrastructure Ltd",
  "LANCER": "Lancer Containers Lines Ltd",
  "WELSPUNENT": "Welspun Enterprises Ltd",
  "KNRCON": "KNR Constructions Ltd",
  "PSPPROJECT": "PSP Projects Ltd",
  "CAPACITE": "Capacit'e Infraprojects Ltd",
  "ASHOKA": "Ashoka Buildcon Ltd",
  "SADBHAV": "Sadbhav Engineering Ltd",
  "HGINFRA": "H.G. Infra Engineering Ltd",
  "IRB": "IRB Infrastructure Developers Ltd",
  "MBLINFRA": "MBL Infrastructures Ltd",
  "NCC": "NCC Ltd",
  "PNCINFRA": "PNC Infratech Ltd",
  "SIMPLE": "Simplex Infrastructures Ltd",
  "WELSPUNIND": "Welspun India Ltd",
  "WELENT": "Welspun Enterprises Ltd",
  "WSTCSTPAPR": "West Coast Paper Mills Ltd",
  "BALLARPUR": "Ballarpur Industries Ltd",
  "TNPETRO": "Tamilnadu Petroproducts Ltd",
  "AMRUTANJAN": "Amrutanjan Health Care Ltd",
  "CARERATING": "CARE Ratings Ltd",
  "CRISIL": "CRISIL Ltd",
  "ICRA": "ICRA Ltd",
  "SCIL": "Shipping Corporation of India Ltd",
  "GESHIP": "Great Eastern Shipping Company Ltd",
  "TCI": "Transport Corporation of India Ltd",
  "WIT": "Wipro Ltd",
  "IBN": "ICICI Bank Ltd",
  "HDB": "HDFC Bank Ltd",
  "TTM": "Tata Motors Ltd",
  "RDY": "Dr. Reddy's Laboratories",
  "WNS": "WNS Global Services",
  "SIFY": "Sify Technologies Ltd",
  "YTRA": "Yatra Online Inc",
};

// Also export for module usage if needed
if (typeof module !== 'undefined' && module.exports) {
  module.exports = INDIAN_COMPANIES;
}